.gitignore, Cargo.lock, examples/ex_1.rs, examples/ex_2.rs, examples/ex_3.rs, examples/ex_4.rs, examples/ex_5.rs, src/constants.rs, src/ncurses.rs
Fixes:
* Macro arguments are not allowed to have 2 `expr` designators next to eachother without a seperating character (I replaced the space with a `,`).
* `int` -> `isize`, `uint` -> `usize` (not needed, but we might as well change it now).
* Changes in the `ffi` module.
PS: I'm new to git, so if I did anything wrong, please tell me :smile:
=> Fix macro def

Makefile
Some argument names in rustc nightly seem to have been changed.
=> Fix build for rustc nightly

.travis.yml, examples/ex_3.rs, examples/ex_5.rs
This change is necessary for the examples to build since io was renamed to old_io.
=> Changed 'std::io' -> 'std::old_io' in examples.

Cargo.toml
I'm relatively new to rust, but I've updated your cargo.toml to be compatible with crates.io, and I've published the most recent version of it after reading your comment in the thread about it your interest in finding someone to do it.
Right now however, it shows my github username as the 'owner' of the crate on crates.io, I would be more than happy to add you as the owner (you just need to link your github account to crates.io and generate a token http://doc.crates.io/crates-io.html#publishing-crates)
I hope I haven't jumped the gun by publishing your library to crates, it's just that there are no other rust ncurses libs around.
=> update cargo.toml for crates.io

Cargo.toml, src/ll.rs, src/ncurses.rs
This PR solves various error trying to compile ncurses-rs with the latest rust beta version.
Please note that the examples do not build with the current rust version. I did refrain from fixing those errors because I don't know enough about the internals of ncurses and don't want to introduce bugs into testing code.
The main library however does compile without any errors or warnings.
=> updated to rust-1.0.0 beta

Cargo.toml, src/ll.rs, src/ncurses.rs, src/panel/ll.rs, src/panel/mod.rs, src/panel/wrapper.rs
This pull request adds panel support as an optional feature to the crate.
Even though the penal functions reside in an own library it makes no sense to create a separate crate because they are strictly dependend on ncurses and just implement a few additional features. Feel free to refuse this pull request if you disagree with my opinion.
Otherwise I would look into implementing the menus and forms features as well.
=> added panel support

Cargo.toml, README.md, examples/ex_5.rs, examples/ex_6.rs, src/menu/constants.rs, src/menu/ll.rs, src/menu/mod.rs, src/menu/wrapper.rs, src/ncurses.rs
This pull request adds menu support as an optional feature to the crate.
I meant to add this feature for a while but couldn't because it wasn't possible to allocate a C string in Rust and transfer ownership to C without leaking. This [feature](https://github.com/rust-lang/rust/pull/25777) has been finally added to rust recently.
It has only been added to nightly and NOT yet to rust stable.
=> Add menu support

examples/ex_5.rs, src/ll.rs, src/menu/ll.rs, src/menu/wrapper.rs, src/ncurses.rs, src/panel/ll.rs, src/panel/wrapper.rs
This PR fixes calls to deprecated functions in the menu mod as well as some other minor stuff.
* The menu mod unfortuanitly still requires rust nightly on which ``into_ptr`` and ``from_ptr`` have been renamed to ``into_raw`` and ``from_raw``
* Changed the menu example to only compile if the menu feature is enabled to avoid errors when executing ``cargo test``
* Fixed the ``warning: found zero-size struct in foreign module, consider adding a member to this struct, #[warn(improper_ctypes)] on by default`` warnings
=> Fix deprecated functions in menu mod

src/ncurses.rs
Probably sound for a const pointer.
Meant to fix https://github.com/jeaye/ncurses-rs/issues/99
=> Fix compilation on arm using nightly rust 1.6

src/ll.rs, src/ncurses.rs
In my copy of ncurses.h, `NCURSES_ATTR_T` is #defined as `int`, so the types are the same in the C API. All of the documentation I can find lists the same type for both sets of functions also, so I think that the different signatures in the header file is just a result of auto-generating function prototypes.
=> Make type of wattron, wattroff, wattrset consistent with non-window versions

src/ncurses.rs
=> Fix handling of pointer returned by `ll::setlocale`.

examples/ex_7.rs, src/ll.rs, src/ncurses.rs
This is WIP, just wanted your thoughts on the implementation.
This exposes [`wget_wch`](http://linux.die.net/man/3/get_wch), which is like `getch` but gets a wide character. I've wrapped it in a more Rust-friendly API: the original function takes a pointer to the location to store the input and returns a result indicating whether the character is a keycode or a character. The exposed version returns an enum instead. If you like this approach, I can wrap the rest of the functions.
TODO:
Also, I noticed that the makefile doesn't quite work on my system, but Cargo can build the examples by simply adding them as binary targets. Would you be interested in a PR to convert to that way of building the examples?
=> Expose wget_wch

README.md
The `bin` directory didn't build for me (OSX Yosemite), and as someone new to Rust, I struggled to run these examples.
=> Better documentation for running examples

examples/ex_2.rs, examples/ex_3.rs, examples/ex_4.rs, examples/ex_6.rs, examples/ex_7.rs, src/constants.rs, src/ncurses.rs
Accessing extern static variables is unsafe with the latest rust nightlies.
This PR wraps these variables in an internal module, and exposes safe getter functions instead.
=> Wrap extern static constants in safe functions

README.md, examples/ex_8.rs, src/constants.rs, src/ll.rs, src/ncurses.rs
Fixes #80 
Changes:
- `chtype` should be `u32` on 64-bit platforms
- Use a reference to the `acs_map` array instead of directly indexing it (the latter seems to cause Rust to index into random memory, because when directly using the array, it'll first try to copy it, then return the copy - but since the array is 0-size, it just does nothing and expects that you won't index it)
=> Fix ACS characters

.gitignore, examples/ex_5.rs, examples/ex_7.rs
Since mmask_t is (so far as I can tell) pretty much never going to be a u64, I replaced u64 with mmask_t on line 28.  I also added an exception for vim swp files into .gitignore, since they should pretty much never be included in a repo.
=> ex_7 compile error fix

Cargo.toml, build.rs, src/ll.rs, src/ncurses.rs
Hi,
Here is a commit to solve the problems due to the size of `chtype`.
It's not the first time there are problems with the size of `chtype`. I found that it was reported (and solved) in #44, but a recent commit (6064435c284c20d31fd6aaf82b13d093fc0eae91) reintroduced the bug. This causes segmentation fault on some systems: I got hit by this bug when using Cursive on a Debian Jessie. Recent issues, #119 and #120, seems related as well.
The problem is not that easy to solve because the size of `chtype` depends on several parameters (see the commit message of this patch for the gory details), and the only reliable way to define it seems to use a build script.
Note that this is the first time I try to use build.rs (and I'm a beginner with Rust), I don't know if there are good practice to …
=> Add a build script to deal with `chtype`

src/ll.rs
On macOS, the "wide" features are directly part of the `ncurses` library, and there is no `ncursesw`.
Linking to `ncursesw` is therefore a compilation error on macOS.
=> Don't link to ncursesw on macos

Cargo.toml, build.rs
This depends on the OS, but use pkg-config to discover what flags rust needs to pass when linking the resulting program.
Under opensuse for example, it was trying to link without extra parameters against -lncurses, but that was matching ncurses version 6, which was missing for example the ::LINES() symbol, producing linking errors.
It first tries to go from the most specific pkg-config sometimes called `ncurses5`. If that fails, it should fallback to `ncurses`.
=> Use pkg-config to provide correct link flags (-l, -L)

Cargo.toml
I have linux distribution where ncurses
split into ncurses and tinfo. pkg-config
return right link flags, so it would be good to have
ncurses-rs on crates.io with this fix.
=> Version BUMP

examples/ex_3.rs
The example code (I think the 3rd example) had a small bug. When you page forward, the pager was eating chars which should instead be printed.
The fix consisted of making an 'else' branch execute on every iteration.
=> small bug in example code: pager eating characters

src/menu/ll.rs
I've been having some problems using the `menu` functionality along side the `wide` feature on the latest Ubuntu (Fedora works fine), seeing random letters such as cyrillic instead of the normal text.
I was able to replicate this in the repo itself using this command:
```bash
cargo run --example ex_5 --features "menu wide"
```
But bare in mind that the command above still works okay on certain linux distros (and versions).
This PR addresses this and correctly links `menuw` instead of `menu` when using `wide`.
I imagine something similar is needed for `panel` as well, but so far I haven't had problems using it alongside `wide`.
=>  Fix menu link name when using the wide feature

src/ll.rs, src/ncurses.rs
Fixed `wgetnstr` and implemented rest of `*getnstr`-family through call to `wgetnstr`. Unfortunately I had to change type of string argument in `ll::wgetnstr` from `char_p` to `*const u8`.
=> Fix getnstr family functions

src/menu/ll.rs, src/menu/wrapper.rs
free the item's name and description.
then free the item itself.
I'm surprised nobody complains as it caused segfault
=> menu: fix free_item

src/ncurses.rs
So it can return None when no name is found.
(Previous behaviour would segfault.)
Fixes #138
=> Return Option<String> from keyname(i32)

src/ll.rs, src/ncurses.rs
Add the three resize_term functions (resize_term, resizeterm, is_term_resized). I don't see any reason for these to not be a part of the library.
For reference, see http://invisible-island.net/ncurses/man/resizeterm.3x.html or the ncurses man page (specifically the resizeterm man page).
=> Add resize_term functions

examples/ex_1.rs
This PR adds a parethesis in [examples/ex_1.rs](https://github.com/jeaye/ncurses-rs/compare/master...dsprenkels:patch-1#diff-27738e418fe65c03484caafb0985e073). Without it, compilation failed, resulting in syntax error.
=> Fix closing parenthesis in example 1

src/constants.rs, src/lib.rs, src/ll.rs
This commit adds Debug implementations for all exported public types, and enables the `missing_debug_implementations` lint.
It also fixes some minor warnings in the other commits.
=> Add missing Debug implementations

build.rs
This forces the crate to relink the library if the user changes the
library search path. Otherwise, the old library would be reused, which
can cause surprising behavior.
=> rerun the build script if PKG_CONFIG_PATH changes

Cargo.toml, src/lib.rs, src/ll.rs
Fixes #154 
I put this behind a feature, because I'm not sure that there's a smarter way to detect ncurses 6.
I used the following test program to test this:
```rust
extern crate ncurses;
use std::process;
use ncurses::*;
fn failed() {
endwin();
println!("failed");
process::exit(1);
}
fn main() {
initscr();
start_color();
let r = init_extended_color(COLOR_RED.into(), 255 * 1000 / 256, 100 * 1000 / 256, 0);
if r != OK {
failed();
}
let r = init_extended_pair(2, COLOR_RED.into(), COLOR_BLACK.into());
if r != OK {
failed();
}
attron(COLOR_PAIR(2));
printw("TRUECOLOR");
refresh();
getch();
endwin();
}
```
=> add extended color functions

src/constants.rs
Among other uses, it allows dependent libraries to trigger their own `mouse_v1` feature based on this constant without the need for the same C-program-compilation trick.
=> Add NCURSES_MOUSE_VERSION constant

src/lib.rs
=> Marked printw function as deprecated

src/lib.rs
including all functions that utilize this and nothing else.
This allows developers to create constants using these functions as this is possible in normal ncurses
- requires `rust>=1.31`
This might be a bit early as a lot of people are still on 1.29
=> change NCURSES_BITS() to const fn

README.md, build.rs
To facilitate the usage in a non-standard environment, this PR would like to add support for setting options via environment variables specific to `ncurses-rs`.
The variables are prefixed by `NCURSES_RS`.
Most importantly, it allows to pass compiler flags for the compilation of the test program in `build.rs` via `NCURSES_RS_CFLAGS`.
The `README` is updated with a description of the variables.
=> Environment variables for non-standard ncurses

src/lib.rs
The wrapper for the ncurses `setlocale()` function converts the provided locale `&str` to a C string by creating a `std::ffi::CString`, then passing its inner pointer on to the ncurses function. This inner pointer outlived the `CString`'s temporary lifetime, so the data it pointed to was undefined when calling `setlocale()`. The fix is to bind the `CString` to a variable, thus extending its lifetime.
Most of the time this does not result in bad behavior, but if the memory being referred to by the pointer is overwritten before the call to `setlocale()`, then a garbage locale string may be used. Unable to find the locale, libc will fall back to a "C" locale, and attempts to print most Unicode characters will result in garbage characters being displayed on the terminal.
I haven't been able …
=> Fix memory corruption in locale string

src/lib.rs
Simply changes the argument names to match `curses.h`.
The naming change doesn't change the purpose of the arguments so there will be no compatibility issues, the names just reflect their actual use now.
=> Flipped `x` and `y` argument names in `derwin` to match `curses.h`.

build.rs, src/lib.rs
Formatted build.rs - aligned indents to 4 spaces
Fixed the warning in src/lib.rs - _unnecessary braces around block return value_
=> Fixed issue #198

src/constants.rs, src/lib.rs, src/ll.rs
This removes the `setlocale` binding, instead relying on the one from libc.
It also re-exports the `LC_ALL` & cie constants from libc, rather than re-defining them here.
This is more portable: `libc` goes to great length to support many platforms (with platform-dependents constants and links), no need to re-invent the wheel here.
Concretely, this fixes an issue with NetBSD where `setlocale` should actually link to `__setlocale50`. `libc` does it correctly, so let's just take that.
=> Use libc::setlocale

src/menu/wrapper.rs
fixes https://github.com/jeaye/ncurses-rs/issues/193
=> for building on arm64

build.rs
`NCURSES_MOUSE_VERSION` is not defined in NetBSD Curses; This patch checks for NetBSD curses as NetBSD curses uses `#define _CURSES_H_` instead of `#define __NCURSES_H`
=> Fix build for NetBSD Curses

build.rs, src/lib.rs, src/ll.rs
Addresses bug #209 
I hope this should be all.
Tests seem to still work.
Related issues:
* https://github.com/jeaye/ncurses-rs/issues/172
* https://github.com/RustSec/advisory-db/issues/106
* https://github.com/jeaye/ncurses-rs/issues/149
* https://github.com/jeaye/ncurses-rs/issues/125
=> Fix gotchas that could cause crashes or worse
